# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OnglxDeploy < Formula
  desc "Deploy AI APIs to AWS in 30 seconds with 85% cost savings"
  homepage "https://onglx.dev"
  version "0.1.17"
  license "MIT"

  depends_on "aws-cli" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onglx/deploy/releases/download/v0.1.17/deploy_Darwin_x86_64.tar.gz"
      sha256 "c90287ebe47f965442bdd3410ac7b60b94a322264fdbfb2575b97809e08d3359"

      def install
        bin.install "onglx-deploy"

        # Install shell completions
        generate_completions_from_executable(bin/"onglx-deploy", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onglx/deploy/releases/download/v0.1.17/deploy_Darwin_arm64.tar.gz"
      sha256 "7914923e414d209c6f04b01496afd812992615e27ecc22b02c562c62335bf1b1"

      def install
        bin.install "onglx-deploy"

        # Install shell completions
        generate_completions_from_executable(bin/"onglx-deploy", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/onglx/deploy/releases/download/v0.1.17/deploy_Linux_x86_64.tar.gz"
      sha256 "84b3e40ff48ecef7e84b6ad03d3b9b6cf8c2b90c4a18ba7d3b21ad3faa10fe82"

      def install
        bin.install "onglx-deploy"

        # Install shell completions
        generate_completions_from_executable(bin/"onglx-deploy", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onglx/deploy/releases/download/v0.1.17/deploy_Linux_arm64.tar.gz"
      sha256 "ad0c2536b0b9a2b14e8a9b98c77bde1a8b2bb1b5a8cf60eb59f6b5b8b1b3b3b3"

      def install
        bin.install "onglx-deploy"

        # Install shell completions
        generate_completions_from_executable(bin/"onglx-deploy", "completion")
      end
    end
  end

  test do
    system "#{bin}/onglx-deploy", "version"
  end
end